server:
  port: 8888

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    config:
      uri: http://config-server:5555

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clients/**
          filters:
            - StripPrefix=1

        - id: produit-service
          uri: lb://produit-service
          predicates:
            - Path=/produits/**
          filters:
            - StripPrefix=1

        - id: facture-service
          uri: lb://facture-service
          predicates:
            - Path=/factures/**
            - Path=/factureLignes/**
          filters:
            - StripPrefix=1

        - id: reglement-service
          uri: lb://reglement-service
          predicates:
            - Path=/reglements/**
          filters:
            - StripPrefix=1

        - id: authentification-service
          uri: lb://authentification-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  client:
    config:
      default:
        url: http://gateway-service:8888
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
