jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - authentification-service
          - client-service
          - produit-service
          - factureservice
          - reglement-service
          - eureka-discoveryservice
          - config-service
          - gatewayservice

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image for ${{ matrix.service }}
      run: |
        IMAGE_NAME=$(basename ${{ matrix.service }} | sed 's/-service//g')
        docker build -t $IMAGE_NAME ./${{ matrix.service }}
        docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
    - name: Check Docker image on Docker Hub
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
