name: Docker Build & Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - authentification-service
          - client-service
          - produit-service
          - factureservice
          - reglement-service
          - eureka-discoveryservice
          - config-service
          - gatewayservice

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker image for ${{ matrix.service }}
      run: |
        SERVICE_NAME=${{ matrix.service }}
        IMAGE_NAME=$(basename $SERVICE_NAME)  # Keep full service name
        docker build -t $IMAGE_NAME ./$SERVICE_NAME
        docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    - name: Verify pushed image on Docker Hub
      run: |
        SERVICE_NAME=${{ matrix.service }}
        IMAGE_NAME=$(basename $SERVICE_NAME)
        docker pull ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
